# fly.toml app configuration file generated for tara-receipt-server on 2025-02-14T00:49:53+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tara-receipt-server'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
